adminn/urls.py
from django.conf.urls import url

from adminn.views import adminIndex, gameOps, userOps, companyOps

app_name = 'adminn'

urlpatterns = [

    url(r'^$', adminIndex.admin_index, name='index'),
    url(r'^createcompany/$', companyOps.create_company, name='create_company'),
    url(r'^listcompany/$', companyOps.list_company, name='list_company'),
    url(r'^listgame/$', gameOps.list_game, name="list_game"),
    url(r'^addgame/$', gameOps.add_game, name='add_game'),
    url(r'^deletegame/$', gameOps.delete_game, name='delete_game'),
    url(r'^userlist/$', userOps.user_list, name='user_list'),
    url(r'^deleteuser/$', userOps.delete_user, name='delete_user'),
    url(r'^ordertable/$', userOps.order_table, name='order_table'),
    url(r'^deletecompany/$', companyOps.delete_company, name='company_delete'),
    url(r'^banuser/$', userOps.ban_user, name='ban_user'),

]

epin/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^games/', include('games.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^sales/', include('sales.urls')),
    url(r'^adminn/', include('adminn.urls')),
]

games/urls.py
from django.conf.urls import url

from games import views

app_name = 'games'

urlpatterns = [
    url(r'^games_json/$', views.games_json, name='games_json'),
    url(r'^game_detail_search/$', views.generate_detail_html, name="detail_search"),
    url(r'^platform_json/$', views.platform_json, name="platform_json"),
    url(r'^game_detail/(?P<game_name>[\w|\W]+)$', views.generate_detail_html, name="game_detail"),
    url(r'^search/$', views.SearchView, name="search_game"),
    url(r'^all/$', views.all, name="all_game"),

]

home/urls.py
from django.conf.urls import url

from home import views

app_name = 'home'

urlpatterns = [

    url(r'^$', views.index, name='index'),
]

sales/urls.py
from django.conf.urls import url

from sales import views

app_name = 'sales'

urlpatterns = [
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^addtocart/$', views.addtocart, name='addtocart'),
    url(r'^update_cart/$', views.update_cart, name='update_cart'),
    url(r'^deletecartitem/$', views.deletecartitem, name='deletecartitem'),
    url(r'^cart_json/$', views.cart_json, name='cart_json'),
]

users/urls.py
from django.conf.urls import url

from users.views import userEntry, userAuth

app_name = 'users'

urlpatterns = [
    url(r'^profile/$', userEntry.profile, name='profile'),
    url(r'^register/$', userEntry.register, name='register'),
    url(r'^login/$', userEntry.login, name='login'),
    url(r'^logout/$', userEntry.logout, name='logout'),
    url(r'^auth_login/$', userAuth.auth_login, name='auth_login')
]

home/models.py
# Create your models here.

home/views.py
from django.shortcuts import render

from adminn.models.gameModels import GameEventClass


def index(request):
    model = GameEventClass()
    platform = model.list_platform()
    pc_games = model.pc_games(1)
    mobil_games = model.mobil_games(2)
    playstation_games = model.playstation_games(3)
    xbox_games = model.xbox_games(4)
    return render(request, "index.html", {"platforms": platform,
                                          "pc_games": pc_games[:5],
                                          "mobil_games": mobil_games,
                                          "xbox_games": xbox_games,
                                          "playstation_games": playstation_games})

home/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/cartlist.css' %}">
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/Pretty-Header.css' %}">
    <link rel="stylesheet" href="{% static 'css/Pretty-Footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="shortcut icon" href="{%  static 'images/favicon.ico' %}">
    <script src="{% static 'js/validationForm_ajax.js' %}"></script>

</head>
<style>
    .m0 {
        margin: 0;
    }
</style>
<body>
<div class="container">
    <nav class="navbar navbar-default custom-header">
        <div class="container">
            <div class="navbar-header"><a class="navbar-brand navbar-link"
                                          href="{% url 'home:index' %}">Epin<span>World </span> </a>
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse"><span
                        class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span
                        class="icon-bar"></span><span class="icon-bar"></span></button>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav links">
                    <li role="presentation"><a href="{% url 'games:all_game' %}"> Oyunlar </a></li>
                    <li role="presentation"><a href="{% url 'home:index' %}"> Hakkında </a></li>
                    <li role="presentation"><a href="{% url 'home:index' %}"> Yardım </a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right userlinks">
                    {% if request.session.is_logged %}
                    {% if request.session.admin_id == 1 %}
                    <span style="color: white; margin-right: 10px;">Admin bey hoşgeldiniz efenim</span>
                    <a href="{% url 'adminn:index' %}" class="btn btn-primary button1" role="button">Admin</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary button2" role="button">Çıkış</a>
                    {% else %}
                    <span style="color: white; margin-right: 10px;">Hoşgeldin {{ request.session.username }}</span>
                    <a href="{% url 'users:profile' %}" class="btn btn-primary button1" role="button">Profil</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary button2" role="button">Çıkış</a>
                    {% endif %}
                    {% else %}
                    <a href="{% url 'users:register' %}" class="btn btn-primary button1" role="button">Üye Ol</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary button2" role="button">Giriş</a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>
<header>
    <div class="container">
        <hr>
        <div class="row">
            <div class="col-md-6">
                <form action="{% url 'games:search_game' %}" method="post">{% csrf_token %}
                    <div id="custom-search-input">
                        <div class="col-md-6 input-group">
                            <input type="text" name="search_game" id="oyunArama" class="form-control input-lg"
                                   style="color: white;" placeholder="Oyun Ara..."/>
                            <span class="input-group-btn">
                                    <button type="submit" class="btn btn-info btn-lg" value="ARA" type="button">
                                        <i class="fa fa-search" aria-hidden="true"
                                           style="font-size: 23px; color: #eb3a3a;"></i>
                                    </button>
                            </span>
                            <div id="results" class="list-group">
                                <div class="ui-widget">

                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-6">
                <div id="mycart" class="dropdown cart">
                    <button class="btn dropdown-toggle cart" type="button" data-toggle="dropdown">
                        <i class="fa fa-shopping-cart carticon" aria-hidden="true"></i>Sepet<span class="badge">{{ request.session.cart|length }}</span>
                        <span class="caret" style="color: white; margin-left: 5px"></span></button>
                    <ul class="dropdown-menu dropdown-cart" style="right:0; left: auto;" role="menu">
                        <div class="cart-header">
                            <i class="fa fa-shopping-cart cart-icon"
                               style="font-size: 25px; margin-left: 10px; color: rgba(117, 236, 165, 0.9);"></i><span
                                class="badge">{{ request.session.cart|length }}</span>
                            <div class="shopping-cart-total">
                                <span>Toplam:</span>
                                <span class="cart-total">{{request.session.cartTotal}}₺</span>
                            </div>
                        </div>
                        {% if request.session.cart|length == 0 %}
                        <p style="text-align: center; color: white; margin-top: 10px;"> Sepet boş.</p>
                        {% else %}
                        {% for item in request.session.cart %}
                        <li>
                                    <span class="item">
                                        <span class="item-left">
                                            <img src="{% static '' %}{{item.logo}}" class="img-rounded" alt=""/>
                                            <span class="item-info">
                                                <span class="item-name">{{ item.game_name }}</span><br>
                                                <span class="item-quantity">{{ item.quantity }}</span>
                                                <label>x</label>
                                                <span class="item-price">{{ item.game_price }}</span>
                                            </span>
                                        </span>
                                        <span class="item-right">
                                            <button value="{{ item.game_id }}" onclick="removeCartItem()"
                                                    class="btn btn-xs btn-danger pull-right"><i class="fa fa-times"
                                                                                                aria-hidden="true"></i></button>
                                        </span>
                                    </span>
                        </li>
                        {% endfor %}
                        <li class="divider"></li>
                        <li><a class="text-center" style="color: white;" href="{% url 'sales:checkout' %}">Sepete
                            Git</a></li>

                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <hr>
    </div>
</header>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<div class="container">
    <footer>
        <div class="row">
            <div class="col-md-4 col-sm-6 footer-navigation">
                <h3><a href="#">Epin<span>World </span></a></h3>
                <p class="links"><a href="{% url 'home:index' %}">Anasayfa</a><strong> · </strong>
                    <a href="{% url 'games:all_game' %}">Oyunlar</a><strong> · </strong>
                    <a href="{% url 'users:profile' %}">Profil</a></p>
                <p class="company-name">EpinWorld © 2017 </p>
            </div>
            <div class="col-md-4 col-sm-6 footer-contacts">
                <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                    <p><span class="new-line-span">İTÜ Ayazağa</span> İstanbul, Türkiye</p>
                </div>
                <div><i class="fa fa-phone footer-contacts-icon"></i>
                    <p class="footer-center-info email text-left"> +90 212 2255 723</p>
                </div>
                <div><i class="fa fa-envelope footer-contacts-icon"></i>
                    <p>info@sc3.io</p>
                </div>
            </div>
            <div class="clearfix visible-sm-block"></div>
            <div class="col-md-4 footer-about">
                <h4>Adresimiz</h4>
                <p> İTÜ Ayazağa Kampüsü,
                    UYBHM. Binası No:2
                    Sarıyer/İstanbul
                </p>
                <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i
                        class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i
                        class="fa fa-github"></i></a></div>
            </div>
        </div>
    </footer>
</div>
<script>
    function removeCartItem() {
        $(".item").on("click", "button", function () {
            var game_id = $(this).val();

            $.ajax({
                type: "POST",
                url: "{% url 'sales:deletecartitem' %}",
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    game_id: game_id
                },
                success: function () {
                    $("#mycart").load(location.href + " #mycart>*", "");
                }
            });
        });
    }
</script>
<script>
    var search_list = [];
    $.ajax({
        type: 'GET',
        url: '{% url "games:games_json"%}',
        data: {get_param: 'value'},
        dataType: 'json',
        success: function (data) {
            var json = data;
            $.each(json, function (i, item) {
                search_list.push(json[i].game_name)
            });
            $('#oyunArama').autocomplete({
                minLength: 1,
                source: search_list,
                select: function (event, ui) {
                    $('#oyunArat').append(search_list[ui.item]);
                }
            });
        }
    });
</script>

<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
</body>
</html>

home/templates/index.html
{% extends 'base-with-category.html' %}
{% load staticfiles %}

{% block title %}Epin World{% endblock %}
<!-- Page Content -->
{% block content %}

<link rel="stylesheet" href="{% static 'css/shop-homepage.css' %}">

<div class="col-md-9" style="margin-top: 20px;">
    <div class="row carousel-holder">
        <div class="col-md-12">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <a href="">
                            <img id="carousel1" class="slide-image img-responsive" src="http://placehold.it/800x300"
                                 alt="">
                        </a>
                    </div>
                    <div class="item">
                        <a href="">
                            <img id="carousel2" class="slide-image img-responsive" src="http://placehold.it/800x300"
                                 alt="">
                        </a>
                    </div>
                    <div class="item">
                        <a href="">
                            <img id="carousel3" class="slide-image img-responsive" src="http://placehold.it/800x300"
                                 alt="">
                        </a>
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>

    </div>

    <div id="game-info" class="row">

    </div>

</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript">
    var game_product_footer = "";
    var randNums = [];
    $.ajax({
        type: "GET",
        url: "{% url 'games:games_json'%}",
        data: {get_param: 'value'},
        dataType: "json",
        success: function (data) {
            var json = data;

            $.each(json, function (i) {
                game_product_footer += "<div class='col-sm-4 col-lg-4 col-md-4'><div class='thumbnail homepage'>";
                game_product_footer += '<img class="thumbnail" name="' + json[i].game_id + '" src="static/' + json[i].logo + '"/>';
                game_product_footer += "<div id='product' class='caption'>";
                game_product_footer += "<h4 id='gameprice' class='pull-right'>" + json[i].game_money_price + "₺" + "</h4>";
                game_product_footer += "<h4 id='gamename'> <a href='/games/game_detail/" + json[i].game_name + "'>" + json[i].game_name + "</a></h4>";
                game_product_footer += "<p class='game-desc'>" + json[i].description + "</p></div>";
                game_product_footer += '<button type="button" id="' + json[i].game_id + '" class="btn btn-primary addtocart"   value="' + json[i].game_name + "/" + json[i].game_money_price + '"><span class="glyphicon glyphicon-shopping-cart"></span id="addtocart-text">Sepete Ekle</button></div></div>';

            });
            for (var i = 0; i < json.length; i++) {
                randNums.push(i);
            }
            function shuffle(a) {
                var j, x, i;
                for (i = a.length; i; i--) {
                    j = Math.floor(Math.random() * i);
                    x = a[i - 1];
                    a[i - 1] = a[j];
                    a[j] = x;
                }
            }

            shuffle(randNums);
            for (var j = 0; j < 3; j++) {
                console.log('#carousel' + (j + 1));
                console.log(json[randNums[j]].logo);
                console.log(json[randNums[j]].game_name);
                $('#carousel' + (j + 1)).attr('src', '{% static "" %}' + json[randNums[j]].logo + '');
                $('#carousel' + (j + 1)).parent("a").attr('href', '/games/game_detail/' + json[randNums[j]].game_name + '')
            }
            $('#game-info').append(game_product_footer)
        }
    });

    $("#game-info").on("click", "button", function () {

        $("img").clone().addClass("zoom").appendTo("body");
        setTimeout(function () {
            $(".zoom").remove();
        }, 1000);

        var gid = $(this).attr('id');
        var currentlogo = $("[name=" + gid + "]").attr('src');
        var logo = currentlogo.substr(7);
        var name = $(this).val().split("/")[0];
        var price = $(this).val().split("/")[1];
        $.ajax({
            type: "POST",
            url: "{% url 'sales:addtocart' %}",
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                game_name: name,
                game_id: gid,
                game_price: price,
                logo: logo
            },
            success: function () {

                $("#mycart").load(location.href + " #mycart>*", "");
            }
        });
    });

</script>

<!-- /.container -->
{% endblock %}