epin/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^games/', include('games.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^sales/', include('sales.urls')),
    url(r'^adminn/', include('adminn.urls')),
]

sales/urls.py
from django.conf.urls import url

from sales import views

app_name = 'sales'

urlpatterns = [
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^addtocart/$', views.addtocart, name='addtocart'),
    url(r'^update_cart/$', views.update_cart, name='update_cart'),
    url(r'^deletecartitem/$', views.deletecartitem, name='deletecartitem'),
    url(r'^cart_json/$', views.cart_json, name='cart_json'),
]

sales/views.py
import json

from django.http import HttpResponse, HttpResponseNotAllowed
from django.shortcuts import render

from games.models import GameEventClass


def checkout(request):
    product_list = {}
    total = 0
    if 'cart' in request.session:
        product_list = request.session['cart']
        for item in product_list:
            quantity = int(item['quantity'])
            price = float(item['game_price'])
            subtotal = quantity * price
            item['subtotal'] = subtotal
            total += subtotal
        request.session['cartTotal'] = total
    else:
        return HttpResponse("Your cart is empty")

    return render(request, "checkout.html", {'product_list': product_list})


def update_cart(request):
    game_id = request.POST.get('game_id', ' ')
    newSubtotal = request.POST.get('newSubtotal', ' ')
    quantity = request.POST.get('quantity', ' ')
    if not request.is_ajax() or not request.method == 'POST':
        return HttpResponseNotAllowed(['POST'])

    for item in request.session['cart']:
        if item['game_id'] == game_id:
            item['subtotal'] = newSubtotal
            item['quantity'] = quantity
            break
    return HttpResponse('Done')


def addtocart(request):
    game_id = request.POST.get('game_id', ' ')
    game_name = request.POST.get('game_name', ' ')
    game_price = request.POST.get('game_price', ' ')
    logo = request.POST.get('logo', ' ')

    if 'cart' not in request.session or request.session['cart'] is None:
        request.session['cartTotal'] = 0
        quantity = 1
        request.session['cart'] = [{'game_name': game_name, 'game_price': game_price,
                                    'game_id': game_id, 'quantity': quantity, 'logo': logo}]
        request.session['cartTotal'] = game_price
    else:
        found = False
        for item in request.session['cart']:
            if game_id == item['game_id']:
                qTemp = int(item['quantity'])
                qTemp += 1
                item['quantity'] = qTemp
                found = True
                request.session['cartTotal'] = float(request.session['cartTotal']) + float(item['game_price'])
                break
        if not found:
            game_list = []
            game_list.append(
                {'game_name': game_name, 'game_price': game_price, 'game_id': game_id, 'quantity': 1, 'logo': logo})
            game_list.extend(request.session['cart'])
            del request.session['cart']
            request.session['cart'] = game_list
            if 'cartTotal' not in request.session:
                request.session['cartTotal'] = 0
                request.session['cartTotal'] = float(request.session['cartTotal']) + float(game_price)
            else:
                request.session['cartTotal'] = float(request.session['cartTotal']) + float(game_price)
    return HttpResponse(json.dumps(request.session['cart']))


def deletecartitem(request):
    game_id = request.POST.get('game_id', ' ')

    for item in request.session['cart']:
        if game_id == item['game_id']:
            game_list = []
            game_list.extend(request.session['cart'])
            for i in game_list:
                if i['game_id'] == game_id:
                    game_list.remove(i)

            del request.session['cart']
            request.session['cart'] = game_list
            totalPrice = float(item['quantity']) * float(item['game_price'])
            request.session['cartTotal'] = float(request.session['cartTotal']) - float(totalPrice)

    return HttpResponse(json.dumps(request.session['cart']))


def cart_json(request):
    instance = GameEventClass()
    if 'cart' in request.session:
        cart = []
        for item in request.session['cart']:
            game = instance.get_game_byid(int(item['game_id']))
            cart.append({'game_name': '{}'.format(game[0]['name']), 'quantity': '{}'.format(item['quantity']),
                         'logo': '{}'.format(game[0]['logo']), 'price': '{}'.format(game[0]['price']),
                         'game_id': '{}'.format(game[0]['id'])})
        return HttpResponse(json.dumps(cart), content_type='application/json')
    else:
        return False

sales/templates/checkout.html
{% extends 'base.html' %}
{% load staticfiles %}
<head>
    {% block title %}Sepet{% endblock %}
    <script src="{% static 'js/bootstrap.js' %}"></script>

</head>


{% block content %}

<link rel="stylesheet" href="{% static 'css/form.css' %}">
<div class="checkout-table" id="testing">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
        <div class="form-layout">
            <table id="checkout-table" class="table table-striped">
                <thead>
                <tr>
                    <th>Ürün</th>
                    <th>Adet</th>
                    <th class="text-center">Fiyat</th>
                    <th class="text-center">Toplam</th>
                    <th> </th>
                </tr>
                </thead>
                <tbody>
                {% for product in product_list%}
                <tr id="game-{{product.game_id}}">
                    <td class="col-md-6">
                        <div class="media">
                            <a class="thumbnail pull-left" href="#"> <img class="media-object"
                                                                          src='{% static "" %}{{product.logo}}'
                                                                          style="width: 80px; height: 72px;"> </a>
                            <div class="media-body">
                                <h4 class="media-heading">{{product.game_name}}</h4>
                                <!--<h5 class="media-heading">by Brand name</h5>-->
                            </div>
                        </div>
                    </td>
                    <td class="col-sm-1 col-md-1" style="text-align: center">
                        <input type="number" onchange="newTotal('{{product.game_id}}')"
                               class="form-control product-quantity"
                               value="{{product.quantity}}">
                    </td>
                    <td class="col-sm-1 col-md-1 text-center"><label class="price">{{product.game_price}}₺</label>
                    </td>
                    <td class="col-sm-1 col-md-1 text-center"><label class="subtotal">{{product.subtotal}}₺</label></td>
                    <td class="col-sm-1 col-md-1">
                        <button type="button" onclick="deleteItem('{{product.game_id}}')" class="btn btn-danger">
                            <span class="glyphicon glyphicon-remove"></span> Sil
                        </button>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td><h3>Toplam</h3></td>
                    <td class="text-right"><h3 class="total">{{request.session.cartTotal}}₺</h3></td>
                </tr>
                <tr>
                    <td>  </td>
                    <td>  </td>
                    <td>  </td>
                    <td>
                        <button type="button" class="btn btn-default">
                            <span class="glyphicon glyphicon-shopping-cart"></span> Alışverişe Devam Et
                        </button>
                    </td>
                    <td>
                        <button type="button" class="btn btn-success">
                            Satın Al <span class="glyphicon glyphicon-play"></span>
                        </button>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script>
    function newTotal(id) {
        var quantity = parseInt($("#game-" + id).find(".product-quantity").val());
        var price = parseInt($("#game-" + id).find(".price").text().replace("₺", ""));
        var subtotal = parseInt($("#game-" + id).find(".subtotal").text().replace("₺", ""));
        var total = parseInt($(".total").text().replace("₺", ""));

        var newSubtotal = parseFloat(quantity * price);

        $("#game-" + id).find(".subtotal").text(newSubtotal + '₺');
        $.post("{% url 'sales:update_cart' %}", {
                game_id: id,
                quantity: quantity,
                newSubtotal: newSubtotal,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            function (data) {
                $("#testing").load(location.href + " #testing>*", "");
                $("#mycart").load(location.href + " #mycart>*", "");
            });

    };
    function deleteItem(id) {
        $.ajax({
            type: "POST",
            url: "{% url 'sales:deletecartitem' %}",
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}',
                game_id: id
            },
            success: function () {
                $("#testing").load(location.href + " #testing>*", "");
                $("#mycart").load(location.href + " #mycart>*", "");
            }
        });
    }
</script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
{% endblock %}