adminn/urls.py
from django.conf.urls import url

from adminn.views import adminIndex, gameOps, userOps, companyOps

app_name = 'adminn'

urlpatterns = [

    url(r'^$', adminIndex.admin_index, name='index'),
    url(r'^createcompany/$', companyOps.create_company, name='create_company'),
    url(r'^listcompany/$', companyOps.list_company, name='list_company'),
    url(r'^listgame/$', gameOps.list_game, name="list_game"),
    url(r'^addgame/$', gameOps.add_game, name='add_game'),
    url(r'^deletegame/$', gameOps.delete_game, name='delete_game'),
    url(r'^userlist/$', userOps.user_list, name='user_list'),
    url(r'^deleteuser/$', userOps.delete_user, name='delete_user'),
    url(r'^ordertable/$', userOps.order_table, name='order_table'),
    url(r'^deletecompany/$', companyOps.delete_company, name='company_delete'),
    url(r'^banuser/$', userOps.ban_user, name='ban_user'),

]

epin/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^games/', include('games.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^sales/', include('sales.urls')),
    url(r'^adminn/', include('adminn.urls')),
]

games/urls.py
from django.conf.urls import url

from games import views

app_name = 'games'

urlpatterns = [
    url(r'^games_json/$', views.games_json, name='games_json'),
    url(r'^game_detail_search/$', views.generate_detail_html, name="detail_search"),
    url(r'^platform_json/$', views.platform_json, name="platform_json"),
    url(r'^game_detail/(?P<game_name>[\w|\W]+)$', views.generate_detail_html, name="game_detail"),
    url(r'^search/$', views.SearchView, name="search_game"),
    url(r'^all/$', views.all, name="all_game"),

]

home/urls.py
from django.conf.urls import url

from home import views

app_name = 'home'

urlpatterns = [

    url(r'^$', views.index, name='index'),
]

sales/urls.py
from django.conf.urls import url

from sales import views

app_name = 'sales'

urlpatterns = [
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^addtocart/$', views.addtocart, name='addtocart'),
    url(r'^update_cart/$', views.update_cart, name='update_cart'),
    url(r'^deletecartitem/$', views.deletecartitem, name='deletecartitem'),
    url(r'^cart_json/$', views.cart_json, name='cart_json'),
]

users/urls.py
from django.conf.urls import url

from users.views import userEntry, userAuth

app_name = 'users'

urlpatterns = [
    url(r'^profile/$', userEntry.profile, name='profile'),
    url(r'^register/$', userEntry.register, name='register'),
    url(r'^login/$', userEntry.login, name='login'),
    url(r'^logout/$', userEntry.logout, name='logout'),
    url(r'^auth_login/$', userAuth.auth_login, name='auth_login')
]

adminn/models.py
from django.db import connection


class AdminEventClass:
    def __init__(self):
        self.cursor = connection.cursor()

    def __del__(self):
        self.cursor.close()

    def dictfetchall(self):
        """ Returns all rows from a cursor as a dict """
        ''' Stackoverflow dan alındı. '''
        desc = self.cursor.description
        return [dict(zip([col[0] for col in desc], row))
                for row in self.cursor.fetchall()]

    def create_company(self, name):
        try:
            self.cursor.execute("INSERT INTO company (name) VALUES ('{}')".format(str(name)))
            return True
        except:
            return False

    def list_company(self):

        try:
            self.cursor.execute("select name from company")

        except:
            return False
        company = self.dictfetchall()
        return company

    def create_game(self, companyName, name, platformName, genreName, price):
        try:

            self.cursor.execute("select id from company WHERE name = '{}'".format(str(companyName)))
            companyId = self.cursor.fetchone()[0]
            self.cursor.execute("select id from platform WHERE name = '{}'".format(str(platformName)))
            platformID = self.cursor.fetchone()[0]
            self.cursor.execute("select id from genre WHERE name = '{}'".format(str(genreName)))
            genreID = self.cursor.fetchone()[0]

            self.cursor.execute("INSERT INTO game (name, company_id, platform_id, price, genre_id )"
                                " VALUES ('{}',{},{},{},{})".format(str(name),companyId,platformID,price,genreID))

            return True
        except:
            return False


    def list_platform(self):

        try:
            self.cursor.execute("Select name from platform")

        except:
            return False

        platform = self.dictfetchall()
        return platform

    def list_category(self):

        try:
            self.cursor.execute("Select name from genre")

        except:
            return False

        category = self.dictfetchall()
        return category

    def list_game(self):

        try:
            self.cursor.execute("Select * from game")

        except:
            return False

        game=self.dictfetchall()
        return game

adminn/models/companyModels.py
from django.db import connection

from utility.cursorutil import dictfetchall


class CompanyEventClass():
    def __init__(self, request_object):
        self.request_object = request_object
        self.cursor = connection.cursor()

    def __del__(self):
        self.cursor.close()

    def create_company(self, cname):

        if self.check_company(cname) is False:
            self.cursor.execute("INSERT INTO company (company_name) VALUES ( '{}' )".format(str(cname)))
            self.cursor.execute("COMMIT;")
            return True
        else:
            return False

    def check_company(self, cname):

        self.cursor.execute("SELECT company_name FROM company WHERE company_name='{}' ".format(cname))
        company = dictfetchall(self.cursor)
        if len(company) <= 0:
            return False
        else:
            return True

    def list_company(self):

        self.cursor.execute("SELECT company_name FROM company ORDER BY created_date DESC ")
        company = dictfetchall(self.cursor)
        if len(company) <= 0:
            return False
        else:
            return company

    def delete_company(self, cname):

        if (self.check_company(cname)):
            try:
                self.cursor.execute("START TRANSACTION;")
                self.cursor.execute(
                    "delete from game where company_id = (select id from company where company_name = '{}')".format(
                        str(cname)))
                self.cursor.execute("delete from company where company_name = '{}' ".format(str(cname)))
                self.cursor.execute("commit;")
                return True
            except:
                return False
        else:
            return False

adminn/models/gameModels.py
from django.db import connection

from utility.cursorutil import dictfetchall


class GameEventClass():
    def __init__(self):
        self.cursor = connection.cursor()

    def __del__(self):
        self.cursor.close()

    def create_game(self, companyName, name, platformName, genreName, price, logo, content):
        try:
            """Game insert ederken company_id genre_id ve platform_id oldugu icin once idlerini bulduk"""
            self.cursor.execute("select id from company WHERE company_name = '{}'".format(str(companyName)))
            companyId = self.cursor.fetchone()[0]
            self.cursor.execute("select id from platform WHERE platform_name = '{}'".format(str(platformName)))
            platformID = self.cursor.fetchone()[0]
            self.cursor.execute("select id from genre WHERE genre_name = '{}'".format(str(genreName)))
            genreID = self.cursor.fetchone()[0]

            self.cursor.execute("INSERT INTO game (name, company_id, platform_id, price, genre_id ,logo, content )"
                                " VALUES ('{}','{}','{}','{}','{}','{}','{}')".format(str(name), companyId, platformID,
                                                                                      price,
                                                                                      genreID, logo, content))

            self.cursor.execute("COMMIT;")
            return True
        except:
            return False

    def get_metadata_of_game(self, game_name):
        self.cursor.execute("SELECT * FROM game WHERE name = {}").format(game_name)
        meta_data = self.cursor.fetchall()
        meta_data_json = []
        for i in meta_data:
            meta_data_json.append(
                {'game_name': '{}'.format(i[1]), 'game_money_price': '{}'.format(i[2]), 'game_content': format(i[9])})

        return meta_data_json

    def list_platform(self):
        try:
            self.cursor.execute("Select platform_name from platform")

        except:
            return False

        platform = dictfetchall(self.cursor)
        return platform

    def list_category(self):
        try:
            self.cursor.execute("Select genre_name from genre ")

        except:
            return False

        category = dictfetchall(self.cursor)
        return category

    def list_game(self):
        try:
            """Inner join ile company_name pltform_name genre_name game tablosu ile cekildi"""
            self.cursor.execute(
                "select game.*,company.company_name,platform.platform_name,genre.genre_name from game INNER JOIN company ON game.company_id = company.id INNER JOIN platform ON game.platform_id = platform.id INNER JOIN genre on game.genre_id = genre.id ORDER BY game.update_date DESC ;")
        except:
            return False

        game = dictfetchall(self.cursor)
        return game

    def delete_game(self, gname):
        try:
            """transaction baslatilip where sorgusu ile oyun silindi"""
            if (self.check_game(gname)):
                self.cursor.execute("start transaction;")
                self.cursor.execute("delete from game where name='{}' ".format(str(gname)))
                self.cursor.execute("commit;")
                return True
            else:
                return False
        except:
            return False

    def check_game(self, gname):

        self.cursor.execute("SELECT name FROM game WHERE name='{}' ".format(gname))
        company = dictfetchall(self.cursor)
        if len(company) <= 0:
            return False
        else:
            return True

    def pc_games(self, id):
        if (id == 1):
            self.cursor.execute("select name from game where platform_id = {}".format(id))
            return dictfetchall(self.cursor)

    def mobil_games(self, id):
        if (id == 2):
            self.cursor.execute("select name from game where platform_id = {}".format(id))
            return dictfetchall(self.cursor)

    def playstation_games(self, id):
        if (id == 3):
            self.cursor.execute("select name from game where platform_id = {}".format(id))
            return dictfetchall(self.cursor)

    def xbox_games(self, id):
        if (id == 4):
            self.cursor.execute("select name from game where platform_id = {}".format(id))
            return dictfetchall(self.cursor)

adminn/views/adminIndex.py
import logging

from django.shortcuts import render

from utility.decorators import is_admin

logging.basicConfig(filename='debug.log', level=logging.DEBUG)


@is_admin
def admin_index(request):
    logging.info("ADMIN PANEL viewed.!")
    return render(request, "admin.html")

adminn/views/companyOps.py
import datetime
import logging

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import redirect, render

from adminn.models.companyModels import CompanyEventClass
from utility.decorators import is_admin

logging.basicConfig(filename='debug.log', level=logging.DEBUG)


@is_admin
def create_company(request):
    """Utkucan """
    """Create company function"""
    """Object Create"""
    instance = CompanyEventClass(request)
    if request.method == "POST":
        """Get company name from form"""
        name = request.POST.get('cname', ' ')
        """If create company"""
        if instance.create_company(name):
            logging.info('company created / {} '.format(datetime.datetime.now()))
            return redirect("adminn:index")

    return render(request, "company.html")


@is_admin
def list_company(request):
    instance = CompanyEventClass(request)
    company = instance.list_company()
    """Use the paginator from django"""
    page = request.GET.get('page', 1)
    """All companies split into 5 pieces"""
    paginator = Paginator(company, 5)
    try:
        companys = paginator.page(page)
        """If page not an integer return page 1"""
    except PageNotAnInteger:
        companys = paginator.page(1)
    except EmptyPage:
        companys = paginator.page(paginator.num_pages)
    return render(request, "companylist.html", {"companys": companys})


@is_admin
def delete_company(request):
    instance = CompanyEventClass(request)
    if request.method == "POST":
        name = request.POST.getlist('name', '')
        for i in range(len(name)):
            instance.delete_company(name[i])

        logging.info('company deleted / {}'.format(datetime.datetime.now()))
        return redirect("adminn:list_company")
    else:
        return redirect("adminn:list_company")

adminn/views/gameOps.py
import datetime
import logging

from PIL import Image
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import redirect, render

from adminn.models.companyModels import CompanyEventClass
from adminn.models.gameModels import GameEventClass
from utility.decorators import is_admin

game_instance = GameEventClass()
logging.basicConfig(filename='debug.log', level=logging.DEBUG)


@is_admin
def add_game(request):
    company_instance = CompanyEventClass(request)
    if request.method == 'POST':
        handle_uploaded_file(request.FILES.get('game_logo'), str(request.FILES.get('game_logo')))
        logo = "images/" + str(request.FILES.get("game_logo"))
        name = request.POST.get('game_name')
        price = request.POST.get('price')
        category = request.POST.get('category')
        company = request.POST.get('company')
        platform = request.POST.get('platform')
        content = request.POST.get('content')

        if game_instance.create_game(company, name, platform, category, price, logo, content):
            logging.info('games added / {}'.format(datetime.datetime.now()))
            return redirect("adminn:index")
        else:
            logging.warning('games could not be added. / {}'.format(datetime.datetime.now()))
            return redirect("adminn:add_game")

    company = company_instance.list_company()
    platform = game_instance.list_platform()
    category = game_instance.list_category()
    return render(request, "add_game.html",
                  {"company": company,
                   "category": category,
                   "platform": platform}
                  )


@is_admin
def list_game(request):
    games = game_instance.list_game()
    page = request.GET.get('page', 1)
    """All game split into 5 pieces"""
    paginator = Paginator(games, 5)
    try:
        game = paginator.page(page)
        """If page not an integer return page 1"""
    except PageNotAnInteger:
        game = paginator.page(1)
    except EmptyPage:
        game = paginator.page(paginator.num_pages)

    return render(request, "list_game.html", {"game": game})


@is_admin
def delete_game(request):
    if request.method == "POST":
        gname = request.POST.get('name', '')
        game_instance.delete_game(gname)
        logging.info('games deleted / {}'.format(datetime.datetime.now()))
        return redirect("adminn:list_game")
    return redirect("adminn:list_game")


def handle_uploaded_file(file, filename):
    img = Image.open(file)
    img.save("./home/static/images/" + filename)

adminn/views/userOps.py
import datetime
import logging

from django.shortcuts import render, redirect

from adminn.models.userModels import UserOperationClass
from utility.decorators import is_admin

logging.basicConfig(filename='debug.log', level=logging.DEBUG)


@is_admin
def user_list(request):
    """ Lists all users in admin panel """
    ''' Sercan : 13.07.2017 '''
    instance = UserOperationClass(request)
    users = instance.list_users()
    logging.info('users listed / {}'.format(datetime.datetime.now()))
    return render(request, "userlist.html", {'users': users})


@is_admin
def delete_user(request):
    """ Deletes user """
    ''' Sercan : 13.07.2017 '''
    request.POST.get()
    instance = UserOperationClass(request)
    instance.delete_user()
    logging.info('User deleted.'.format(datetime.datetime.now()))
    return redirect("adminn:user_list")


@is_admin
def order_table(request):
    return render(request, "ordertable.html")


@is_admin
def ban_user(request):
    """Postdan aldigimiz useri statusunu değistirip yasakliyoruz"""
    if request.method == "POST":
        uname = request.POST.get('name', '')
        instance = UserOperationClass(request)
        instance.ban_user(uname)
        logging.info('user banned. / {}'.format(datetime.datetime.now()))
        return redirect("adminn:user_list")
    else:
        return redirect("adminn:user_list")

adminn/templates/admin.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Admin Panel{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/cartlist.css' %}">
    <link rel="stylesheet" href="{% static 'css/category.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
    <link rel="stylesheet" href="{% static 'css/Pretty-Header.css' %}">
    <link rel="stylesheet" href="{% static 'css/Pretty-Footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop-homepage.css' %}">
    <link rel="shortcut icon" href="{%  static 'images/favicon.ico' %}">

</head>
<style>
    .m0 {
        margin: 0;
    }
</style>
<body>
<div class="container">
    <nav class="navbar navbar-default custom-header">
        <div class="container">
            <div class="navbar-header"><a class="navbar-brand navbar-link"
                                          href="{% url 'home:index' %}">Epin<span>World </span> </a>
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse"><span
                        class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span
                        class="icon-bar"></span><span class="icon-bar"></span></button>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav links">
                    <li role="presentation"><a href="{% url 'games:all_game' %}"> Oyunlar </a></li>
                    <li role="presentation"><a href="{% url 'home:index' %}"> Hakkında</a></li>
                    <li role="presentation"><a href="{% url 'home:index' %}"> Yardım</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right userlinks">
                    {% if request.session.is_logged %}
                    {% if request.session.admin_id == 1 %}
                    <a href="{% url 'adminn:index' %}" class="btn btn-primary button1" role="button">Admin</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary button2" role="button">Çıkış</a>
                    {% else %}
                    <a href="{% url 'users:profile' %}" class="btn btn-primary button1" role="button">Profil</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary button2" role="button">Çıkış</a>
                    {% endif %}
                    {% else %}
                    <a href="{% url 'users:register' %}" class="btn btn-primary button1" role="button">Üye Ol</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary button2" role="button">Giriş</a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>
<header>
    <div class="container">
        <hr>
        <div class="row">
            <div class="col-md-6">
                <form action="{% url 'games:search_game' %}" method="post">{% csrf_token %}
                    <div id="custom-search-input">
                        <div class="input-group col-md-6">
                            <input type="text" id="oyunArama" class="form-control input-lg" style="color: white;"
                                   placeholder="Oyun Ara..."/>
                            <span class="input-group-btn">
                                    <button type="submit" class="btn btn-info btn-lg" type="button">
                                        <i class="fa fa-search" aria-hidden="true"
                                           style="font-size: 23px; color: #eb3a3a;"></i>
                                    </button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-md-6">
                <div id="mycart" class="dropdown cart">
                    <button class="btn dropdown-toggle cart" type="button" data-toggle="dropdown">
                        <i class="fa fa-shopping-cart carticon" aria-hidden="true"></i>Sepet<span class="badge">{{ request.session.cart|length }}</span>
                        <span class="caret" style="color: white; margin-left: 5px"></span></button>
                    <ul class="dropdown-menu dropdown-cart" style="right:0; left: auto;" role="menu">
                        <div class="cart-header">
                            <i class="fa fa-shopping-cart cart-icon"
                               style="font-size: 25px; margin-left: 10px; color: rgba(117, 236, 165, 0.9);"></i><span
                                class="badge">{{ request.session.cart|length }}</span>
                            <div class="shopping-cart-total">
                                <span>Toplam:</span>
                                <span class="cart-total">0</span>
                            </div>
                        </div>
                        {% if request.session.cart|length == 0 %}
                        <p style="text-align: center; color: white; margin-top: 10px;"> Sepet boş.</p>
                        {% else %}
                        {% for item in request.session.cart %}
                        <li>
                                    <span class="item">
                                        <span class="item-left">
                                            <img src="http://lorempixel.com/50/50/" class="img-circle" alt=""/>
                                            <span class="item-info">
                                                <span class="item-name">{{ item.game_name }}</span><br>
                                                <span class="item-quantity">{{ item.quantity }}</span>
                                                <label>x</label>
                                                <span class="item-price">{{ item.game_price }}₺</span>
                                            </span>
                                        </span>
                                        <span class="item-right">
                                            <button value="{{ item.game_id }}" onclick="removeCartItem()"
                                                    class="btn btn-xs btn-danger pull-right"><i class="fa fa-times"
                                                                                                aria-hidden="true"></i></button>
                                        </span>
                                    </span>
                        </li>
                        {% endfor %}
                        <li class="divider"></li>
                        <li><a class="text-center" style="color: white;" href="{% static 'sales:checkout' %}">Sepete
                            Git</a></li>

                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
        <hr>
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="nav-side-menu">
                <div class="brand">Admin Panel</div>
                <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
                <div class="menu-list">
                    <ul id="menu-content" class="menu-content collapse out">
                        <li data-toggle="collapse" data-target="#games" class="collapsed">
                            <a href="#"><i class="fa fa-desktop fa-lg"></i> Oyun <span class="arrow"></span></a>
                        </li>
                        <ul class="sub-menu collapse" id="games">
                            <li><a href="{% url 'adminn:add_game'%}">Oyun Ekle</a></li>
                            <li><a href="{% url 'adminn:list_game' %}">Oyun Listele - Sil</a></li>
                        </ul>


                        <li data-toggle="collapse" data-target="#users" class="collapsed">
                            <a href="#"><i class="fa fa-gamepad fa-lg"></i> Kullanıcı <span class="arrow"></span></a>
                        </li>
                        <ul class="sub-menu collapse" id="users">
                            <li><a href="{% url 'adminn:user_list' %}">Kullanıcı Listeleme - Silme</a></li>
                        </ul>


                        <li data-toggle="collapse" data-target="#sales" class="collapsed">
                            <a href="#"><i class="fa fa-gamepad fa-lg"></i> Siparişler <span class="arrow"></span></a>
                        </li>
                        <ul class="sub-menu collapse" id="sales">
                            <li><a href="{% url 'adminn:order_table' %}">Sipariş Listeleme - Silme</a></li>
                        </ul>
                        <li>


                        <li data-toggle="collapse" data-target="#company" class="collapsed">
                            <a href="#"><i class="fa fa-gamepad fa-lg"></i> Şirketler <span class="arrow"></span></a>
                        </li>
                        <ul class="sub-menu collapse" id="company">
                            <li><a href="{% url 'adminn:create_company' %}">Şirket ekle</a></li>
                            <li><a href="{% url 'adminn:list_company' %}">Şirket Listeleme - Silme</a></li>
                        </ul>
                        <li>
                    </ul>
                </div>
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</div>

<div class="container">
    <footer>
        <div class="row">
            <div class="col-md-4 col-sm-6 footer-navigation">
                <h3><a href="#">Epin<span>World </span></a></h3>
                <p class="links"><a href="{% url 'home:index' %}">Anasayfa</a><strong> · </strong>
                    <a href="{% url 'games:all_game' %}">Oyunlar</a><strong> · </strong>
                    <a href="{% url 'users:profile' %}">Profil</a></p>
                <p class="company-name">EpinWorld © 2017 </p>
            </div>
            <div class="col-md-4 col-sm-6 footer-contacts">
                <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                    <p><span class="new-line-span">İTÜ Ayazağa</span> İstanbul, Türkiye</p>
                </div>
                <div><i class="fa fa-phone footer-contacts-icon"></i>
                    <p class="footer-center-info email text-left"> +90 212 2255 723</p>
                </div>
                <div><i class="fa fa-envelope footer-contacts-icon"></i>
                    <p>info@sc3.io</p>
                </div>
            </div>
            <div class="clearfix visible-sm-block"></div>
            <div class="col-md-4 footer-about">
                <h4>Adresimiz</h4>
                <p> İTÜ Ayazağa Kampüsü,
                    UYBHM. Binası No:2
                    Sarıyer/İstanbul
                </p>
                <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i
                        class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i
                        class="fa fa-github"></i></a></div>
            </div>
        </div>
    </footer>
</div>
<script>
    function removeCartItem() {
        $(".item").on("click", "button", function () {
            var game_id = $(this).val();

            $.ajax({
                type: "POST",
                url: "{% url 'sales:deletecartitem' %}",
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    game_id: game_id
                },
                success: function () {
                    $("#mycart").load(location.href + " #mycart>*", "");
                }
            });
        });
    }

</script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

adminn/templates/company.html
{% extends './admin.html' %}
{% load staticfiles %}
{% block title %}Şirket Ekle{% endblock %}
{% block content %}
<link href="{% static 'css/form.css'%}" rel="stylesheet" type="text/css"/>

<div class="col-md-6">
    <form class="user-form" action="{% url 'adminn:create_company' %}" method="POST">{% csrf_token %}
        <h3>Şirket Ekle</h3>
        <div class="col-md-12">
            <div class="form-layout">
                <label> Şirket Adı: </label>
                <input type="text" name="cname" class="form-control">
            </div>
        </div>
        <div class="col-md-4">
            <button type="submit" style="margin-left: -15px" class="btn btn-block signup-button">Ekle</button>
        </div>
    </form>
</div>
{% endblock %}