adminn/urls.py
from django.conf.urls import url

from adminn.views import adminIndex, gameOps, userOps, companyOps

app_name = 'adminn'

urlpatterns = [

    url(r'^$', adminIndex.admin_index, name='index'),
    url(r'^createcompany/$', companyOps.create_company, name='create_company'),
    url(r'^listcompany/$', companyOps.list_company, name='list_company'),
    url(r'^listgame/$', gameOps.list_game, name="list_game"),
    url(r'^addgame/$', gameOps.add_game, name='add_game'),
    url(r'^deletegame/$', gameOps.delete_game, name='delete_game'),
    url(r'^userlist/$', userOps.user_list, name='user_list'),
    url(r'^deleteuser/$', userOps.delete_user, name='delete_user'),
    url(r'^ordertable/$', userOps.order_table, name='order_table'),
    url(r'^deletecompany/$', companyOps.delete_company, name='company_delete'),
    url(r'^banuser/$', userOps.ban_user, name='ban_user'),

]

epin/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^games/', include('games.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^sales/', include('sales.urls')),
    url(r'^adminn/', include('adminn.urls')),
]

users/urls.py
from django.conf.urls import url

from users.views import userEntry, userAuth

app_name = 'users'

urlpatterns = [
    url(r'^profile/$', userEntry.profile, name='profile'),
    url(r'^register/$', userEntry.register, name='register'),
    url(r'^login/$', userEntry.login, name='login'),
    url(r'^logout/$', userEntry.logout, name='logout'),
    url(r'^auth_login/$', userAuth.auth_login, name='auth_login')
]

users/models.py
import datetime

from django.db import connection

from adminn.models.userModels import UserOperationClass
from utility.cursorutil import dictfetchall


class UserEventClass():
    def __init__(self, request_object):
        self.request_object = request_object
        self.cursor = connection.cursor()
        self.instance = UserOperationClass(request_object)

    def __del__(self):
        self.cursor.close()

    def login_event(self):
        """ Checks if the username and password matches in the database
            Returns username as a dictionary """
        ''' Sercan : 12.07.2017'''
        t1 = self.request_object['username']
        t2 = self.request_object['password']
        if ("'" in t1 or "'" in t2):
            return False
        self.cursor.execute(
            "SELECT username, admin_id FROM users WHERE username='{}' AND password='{}'".format(t1, str(t2)))
        user = dictfetchall(self.cursor)
        return user

    def register_event(self):
        """ User registration: if user already exists in the database
         It return False, otherwise does the registration """
        ''' Sercan : 13.07.2017 '''
        t1 = self.request_object['username']
        t2 = self.request_object['email']
        t3 = self.request_object['password']
        t4 = self.request_object['name']
        t5 = self.request_object['surname']
        full_name = t4 + " " + t5

        if self.instance.check_user() is False:
            self.cursor.execute("INSERT INTO users (username, email, password, full_name, status_id, admin_id)"
                                "VALUES ('{}', '{}', '{}', '{}', '{}', '{}')".format(t1, t2, str(t3), full_name, 1, 2))
            self.cursor.execute("COMMIT;")
        else:
            return False

    def update_lastlogin(self, username):
        """ Gets the username and updates its last login time """
        ''' Sercan : 14.07.2017 '''
        now = datetime.datetime.now()
        self.cursor.execute("UPDATE users SET lastlogin='{}' WHERE username='{}' ".format(now, username))
        self.cursor.execute("COMMIT;")

users/views.py
from django.shortcuts import render, redirect,render_to_response
from django.http import HttpResponse
from .models import EventClass
from users.decorators import is_admin, login_required
import requests
import json
import logging
import datetime
from django.db import connections




cursor = connections['default'].cursor()
logging.basicConfig(filename= 'debug.log' , level= logging.DEBUG)


def language_detector(request):
    language = request.GET.get('language',' ')
    
    request.session['language'] = language
    print("asdassdasdasd " +  request.session['language'] )

    
    try:
        response = render_to_response("{}/index.html".format(request.session['language']))
        response.set_cookie('language','{}'.format(request.session['language']))
        return response

    except:
        response = render_to_response("tr/index.html".format(request.session['language']))
        response.set_cookie('language','{}'.format(request.session['language']))
        return response
def login(request):
    """ Login view: if the user is logged redirects to the index,
    if the user is not logged shows login page """
    ''' Sercan : 11.07.2017 '''

    if 'is_logged' not in request.session:
        try:
            logging.info('login succesful. / {}'.format(datetime.datetime.now()))
            return render(request, "{}/login.html".format(request.session['language']))
        except:
            logging.error('login failed')
            return render(request, "tr/login.html")
    else:
        username = request.session['username']
        if request.session['is_logged'] == False:
            instance = EventClass(request)
            instance.update_lastlogin(username)
        return redirect("users:index")


def auth_login(request):
    """ Login Authentication: gets the user's username and password
      from the html form with POST method and checks the database,
      if user exists, username, password and is_logged variables are
      passed to the session. Then redirects to the index page.
      if user does not exits reloads the login page """
    ''' Sercan : 11.07.2017 '''
    if request.method == "POST":
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user_info = request.POST

        instance = EventClass(user_info)
        instance.update_lastlogin(username)
        user = instance.login_event()

        if len(user) > 0:
            request.session['admin_id'] = user[0]['admin_id']
            request.session['username'] = username
            request.session['password'] = password
            request.session['is_logged'] = True

            return redirect("users:index")

        else:
            return redirect("users:login")


def index(request):

    instance = EventClass(request)
    index_game_data = instance.get_popular_game()
    print(index_game_data)
    return render(request, "{}/index.html".format(request.COOKIES['language']),{'index_game_data':index_game_data})


def register(request):
    """ Registration of the user: gets the user's credentials
      from the html form with POST method and checks the database,
      if user already exists, displays warning message
      if user does not exits and registration is successfull, display ok message """
    ''' Sercan : 12.07.2017 '''

    if request.method == "POST":
        user_info = request.POST
        instance = EventClass(user_info)
        if instance.register_event() is False:
            return HttpResponse("<h1>Registration Failed</h1>")
        else:
            return HttpResponse("<h1>Registration Successfull</h1>")
    return render(request, "{}/register.html".format(request.COOKIES['language']))


@login_required
def profile(request):
    """ User profile page: gets the username from the session and
     passes the user information to profile.html to show in html """
    ''' Sercan : 13.07.2017 '''
    instance = EventClass(request)
    user_info = instance.find_user(request.session['username'])
    if user_info is not False:
        user = user_info
    return render(request, "{}/profile.html".format(request.COOKIES['language']), {'user': user})




# WoodProgrammer
# #Bu method detail.html'i url'den gelen parametreye göre
#generate etmektedir.
#14/07/17 Cuma.
def generate_detail_html(request,game_name):
    r = requests.get('http://localhost:8000/games/games_json/')
    games_data = json.loads(r.text)

    detail_html_data = {}

    k = 0
    for i in  games_data:

        if str(games_data[k]['game_name']) == '{}'.format(game_name):
            print(k)
            detail_html_data = games_data[k]

            break

        else:

            print(games_data[0]['game_name'])

        k += 1

    return  render(request, 'detail.html',{'game_data':detail_html_data})

@is_admin
def oyunekle_finish(request):
    game_name = request.POST.get('game_name','')
    game_money_price = request.POST.get('game_money_price','')
    game_genre = request.POST.get('game_name','')
    game_platform = request.POST.get('platform','')

    instance = EventClass(request)
    instance.game_insert(game_name, game_money_price, game_genre, game_platform)

    return generate_detail_html(request,game_name)

@is_admin
def oyunekle_first(request):

          
    print(request.COOKIES)
    return render(request,"{}/oyunekle.html".format(request.COOKIES['language']))


@is_admin
def oyunsil(request):
    return render(request, "{}/oyunsil.html".format(request.COOKIES['language']))

@is_admin
def companylist(request):
    return render(request, "{}/companylist.html".format(request.COOKIES['language']))

@is_admin
def company(request):
    return render(request, "{}/company.html".format(request.COOKIES['language']))

@login_required
def ordertable(request):
    return render(request, "{}/ordertable.html".format(request.COOKIES['language']),{'lang_data':request.COOKIES['language']})


@is_admin
def adminview(request):
    logging.info("ADMIN PANEL viewed.!")
    return render(request, "{}/admin.html".format(request.COOKIES['language']))


def logout(request):
    """ Logs outs the user by deleting session information
        and renders logout.html """
    ''' Sercan : 13.07.2017 '''
    try:
        request.session.flush()
        logging.info('logout had done. / {}'.format(datetime.datetime.now()))
    except KeyError:
        pass
        logging.error('logout had not done / {}')
    return render(request, "{}/logout.html".format(request.COOKIES['language']))

@is_admin
def create_company(request):
    if request.method == "POST":
        name = request.POST.get('cname', "")
        comp_info = request.POST
        instance = EventClass(comp_info)
        instance.create_company()
        return HttpResponse("<h1>Creating Successful!</h1>")
        logging.info('company created / {}' .format(datetime.datetime.now()))
    return render(request, "{}/company.html".format(request.COOKIES['language']))

@is_admin
def user_list(request):
    """ Lists all users in admin panel """
    ''' Sercan : 13.07.2017 '''
    instance = EventClass(request)
    users = instance.list_users()
    return render(request, "{}/userslist.html".format(request.COOKIES['language']), {'users': users})

@is_admin
def delete_user(request):
    """ Deletes user """
    ''' Sercan : 13.07.2017 '''
    request.POST.get()
    instance = EventClass(request)
    instance.delete_user()
    logging.info('User deleted. / {}'.format(datetime.datetime.now()))
    return redirect("users:user_list")

users/views/userAuth.py
from django.shortcuts import redirect

from users.models import UserEventClass


def auth_login(request):
    """ Login Authentication: gets the user's username and password
      from the html form with POST method and checks the database,
      if user exists, username, password and is_logged variables are
      passed to the session. Then redirects to the index page.
      if user does not exits reloads the login page """
    ''' Sercan : 11.07.2017 '''
    if request.method == "POST":
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user_info = request.POST

        instance = UserEventClass(user_info)
        if (not instance.login_event()):
            return redirect("users:login")
        user = instance.login_event()
        instance.update_lastlogin(username)

        if len(user) > 0:
            request.session['admin_id'] = user[0]['admin_id']
            request.session['username'] = username
            request.session['password'] = password
            request.session['is_logged'] = True

            return redirect("home:index")

        else:
            return redirect("users:login")

users/views/userEntry.py
import logging
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render, redirect

from adminn.models.userModels import UserOperationClass
from users.models import UserEventClass
from utility.decorators import login_required

logging.basicConfig(filename='debug.log', level=logging.DEBUG)


def login(request):
    """ Login view: if the user is logged redirects to the index,
    if the user is not logged shows login page """
    ''' Sercan : 11.07.2017 '''

    if 'is_logged' not in request.session:
        try:
            logging.info('login succesful. / {}'.format(datetime.datetime.now()))
            return render(request, "login.html")
        except:
            logging.error('login failed')
            return render(request, "login.html")
    else:
        username = request.session['username']
        if request.session['is_logged'] is False:
            instance = UserEventClass(request)
            instance.update_lastlogin(username)
        return redirect("users:profile")


@login_required
def logout(request):
    """ Logs outs the user by deleting session information except the cart data
        and renders logout.html """
    ''' Sercan : 13.07.2017 '''
    try:
        for key in list(request.session.keys()):
            if key != 'cart':
                del request.session[key]

        logging.info("logout had done. '{}'".format(datetime.now()))
    except KeyError:
        logging.ERROR('logout had not done')
    return render(request, "logout.html")


def register(request):
    """ Registration of the user: gets the user's credentials
      from the html form with POST method and checks the database,
      if user already exists, displays warning message
      if user does not exits and registration is successfull, display ok message """
    ''' Sercan : 12.07.2017 '''

    if request.method == "POST":
        user_info = request.POST
        instance = UserEventClass(user_info)
        if instance.register_event() is False:
            return HttpResponse("<h1>Registration Failed</h1>")
        else:
            return HttpResponse("<h1>Registration Successfull</h1>")
    return render(request, "register.html")


@login_required
def profile(request):
    """ User profile page: gets the username from the session and
     passes the user information to profile.html to show in html """
    ''' Sercan : 13.07.2017 '''
    instance = UserOperationClass(request)
    user_info = instance.find_user(request.session['username'])
    if user_info is not False:
        user = user_info
    return render(request, "profile.html", {'user': user})

users/templates/tr/admin-tr.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
    {% block title%}<title>Base</title>{% endblock %}

    <!-- JavaScript Files -->
    <script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!--script-->

    <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet" type="text/css"/>
    <!--theme-style-->
    <link href="{% static 'css/style.css'%}" rel="stylesheet" type="text/css"/>
    <!--//theme-style-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script type="application/x-javascript">
         addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }
    </script>
    <!--fonts-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900,900i&amp;subset=cyrillic,cyrillic-ext,latin-ext"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dosis:200,300,400,500,600,700,800&amp;subset=latin-ext"
          rel="stylesheet">

    <!-- this is default skin you can replace that with: dark.css, yellow.css, red.css ect -->
    <link id="pagestyle" rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}"/>
</head>

<div class="header">
    <div class="top-header">
        <div class="container">
            <div class="top-header-left">
                <ul class="support">
                    <li><a href="#"><label> </label></a></li>
                    <li><a href="#">24x7 Canlı<span class="live"> destek</span></a></li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="top-header-right">
                <div class="down-top">
                    <select class="in-drop">
                        <option value="Turkish" class="in-of">Turkish</option>
                        <option value="English" class="in-of">English</option>
                    </select>
                </div>
                <!---->
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="bottom-header">
        <div class="container">
            <div class="header-bottom-left">
                <div class="logo">
                    <a href="/"><img src="{% static 'images/logoo.jpeg'%}" style="width: 300px;height: 100px;" alt=" "/></a>
                </div>
                <div class="search">
                    <input type="text" placeholder="Oyun ara..." value="" onfocus="this.value = '';"
                           onblur="if (this.value == '') {this.value = '';}">
                    <input type="submit" value="ARA">

                </div>
                <div class="clearfix"></div>
            </div>
            <div class="header-bottom-right">
                {% if not user.is_admin %}
                <div class="account"><a href="{% url 'users:profile' %}"><span> </span>Admin</a></div>
                {% else %}
                <div class="account"><a href="{% url 'users:profile' %}"><span> </span>Hesabım</a></div>
                {% endif %}

                <ul class="login">

                    <li><a href="{% url 'users:register' %}"><span> </span>Üye Ol</a></li>
                    |
                    <li><a href="{% url 'users:login' %}">Giriş</a></li>
                </ul>
                <div class="cart"><a href="checkout"><span> </span>Sepet</a></div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!---->











<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="sub-cate">
                <div class=" top-nav rsidebar span_1_of_left">
                    <h3 class="cate">Admin Paneli</h3>
                    <ul class="menu">
                        <li class="item1"><a href="#">Oyun<img class="arrow-img" style="margin-left:113px;"
                                                             src="{% static 'images/arrow1.png' %}"
                                                             alt=""/>
                        </a>
                            <ul class="cute">
                                <li class="subitem1"><a href="{% url 'users:oyunekle'%}">Oyun Ekle</a></li>
                                <li class="subitem2"><a href="{% url 'users:oyunsil' %}">Oyun Listele - Sil</a></li>

                            </ul>
                        </li>
                        <li class="item1"><a href="#">Kullanıcı<img class="arrow-img" style="margin-left:87px;"
                                                             src="{% static 'images/arrow1.png' %}"
                                                             alt=""/>
                        </a>
                            <ul class="cute">
                                <li class="subitem1"><a href="{% url 'users:user_list' %}"> Kullanıcı Listeleme - Silme</a></li>

                            </ul>
                        </li>

                        <li class="item1"><a href="#">Siparişler<img class="arrow-img" style="margin-left:80px;"
                                                             src="{% static 'images/arrow1.png' %}"
                                                             alt=""/>
                        </a>
                            <ul class="cute">
                                <li class="subitem1"><a href="{% url 'users:ordertable' %}">Sipariş Listeleme - Silme</a></li>

                            </ul>
                        </li>

                        <li class="item1"><a href="#" >Şirketler<img  class="arrow-img" style="margin-left:90px;"
                                                             src="{% static 'images/arrow1.png' %}"
                                                             alt="" />
                        </a>
                            <ul class="cute">
                                <li class="subitem1"><a href="{% url 'users:companyy' %}">Şirket ekle</a></li>
                                <li class="subitem3"><a href="{% url 'users:company' %}"> Şirket Listeleme - Silme</a></li>

                            </ul>
                        </li>

                    </ul>
                </div>

                <!--initiate accordion-->
                <script type="text/javascript">
			$(function() {
			    var menu_ul = $('.menu > li > ul'),
			           menu_a  = $('.menu > li > a');
			    menu_ul.hide();
			    menu_a.click(function(e) {
			        e.preventDefault();
			        if(!$(this).hasClass('active')) {
			            menu_a.removeClass('active');
			            menu_ul.filter(':visible').slideUp('normal');
			            $(this).addClass('active').next().stop(true,true).slideDown('normal');
			        } else {
			            $(this).removeClass('active');
			            $(this).next().stop(true,true).slideUp('normal');
			        }
			    });

			});
                </script>
            </div>
        </div>
        {% block content %}
        {% endblock %}
    </div>
</div>
</div>





















<!---->

<div class="clearfix" ></div>
<hr />

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h5 class="title">Oyunlar</h5>
                <ul class="list alt-list">
                    <li><a href="shop-sidebar-left.html"><i
                            class="glyphicon glyphicon-certificate"></i>PC</a>
                    </li>
                    <li><a href="shop-sidebar-left.html"><i class="glyphicon glyphicon-certificate"></i>Mobil</a>
                    </li>
                    <li><a href="shop-sidebar-left.html"><i
                            class="glyphicon glyphicon-certificate"></i>Playstation</a>
                    </li>
                    <li><a href="shop-sidebar-left.html"><i
                            class="glyphicon glyphicon-certificate"></i>Xbox</a>
                    </li>
                </ul>
            </div><!-- end col -->
            <div class="col-sm-4">
                <h5 class="title">Hesap</h5>
                <ul class="list alt-list">
                    <li><a href="my-account.html"><i class="glyphicon glyphicon-certificate"></i>Hesabım</a>
                    </li>
                    <li><a href="cart.html"><i class="glyphicon glyphicon-certificate"></i>Sepetim</a></li>
                    <li><a href="checkout.html"><i class="glyphicon glyphicon-certificate"></i>Ödeme</a></li>
                    <li><a href="help.html"><i class="glyphicon glyphicon-certificate"></i>Yardım</a></li>
                </ul>
            </div><!-- end col -->
            <div class="col-sm-4">
                <h5 class="title">Adresimiz</h5>
                <p>İTÜ Ayazağa Kampüsü,
                    UYBHM. Binası No:2
                    Sarıyer/İstanbul</p>
                <h6 class="text-light"><i class="glyphicon glyphicon-phone"></i> +90 212 225 57 23</h6>
                <h6 class="text-light"><i class="glyphicon glyphicon-envelope"></i> info@sc3.io</h6>
            </div><!-- end col -->
        </div><!-- end row -->

        <hr class="spacer-20">

        <div class="row">
            <div class="col-sm text-center">
                <p class="text-sm">&COPY; 2017. Made with <i class="glyphicon glyphicon-heart"></i> Bootstrap by
                    TRNet</p>
            </div><!-- end col -->
        </div><!-- end row -->
    </div><!-- end container -->
</footer>
<!-- end footer -->

</body>
</html>

users/templates/tr/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title%}<title>Giriş</title>{% endblock %}


{% block content %}
<div class="col-md-6 col-md-offset-4">
    <form class="user-form" action="{% url 'users:auth_login' %}" method="POST">{% csrf_token %}
        <h3>Giriş</h3>
        <div class="col-md-12">
            <div class="form-layout">
                <input type="text" name="username" class="form-control" placeholder="Kullanıcı Adı*">
                <input type="password" name="password" class="form-control" placeholder="Şifre*">
                <div class="col-md-6">
                    <button type="submit" class="btn btn-block signup-button">Giriş</button>
                </div>
            </div>
        </div>
        <div class="col-md-8 register-text">
            <h3 class="text-center">HEMEN ÜYE OL</h3>
            <p>Epinworld e katılarak avantajlı fiyatlara ulaşmak için üye ol.</p>
            <a href="{% static 'users:register' %}" class="btn gray text-center width100"><span>ÜYE OL</span></a> </div>
    </form>
</div>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>

{% endblock %}

users/templates/tr/logout.html
<head>
    {% extends 'base.html' %}
    {% load staticfiles %}
    {% block title%}<title>Çıkış</title>{% endblock %}
</head>
{% block content %}
    {% csrf_token %}
    <h3 style="">Çıkış Yaptınız .</h3>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>

{% endblock %}

users/templates/tr/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<link href="{% static 'css/dashboard.css' %}" rel="stylesheet" type="text/css"/>
<div class="col-md-4 profile-main">
    <ul class="nav nav-pills nav-stacked admin-menu">
        <li class="active"><a class="profile-link" href="" data-target-id="profile"><i
                class="glyphicon glyphicon-user"></i> Profil</a></li>
        <li><a href="" class="profile-link" data-target-id="change-password"><i class="glyphicon glyphicon-lock"></i> Şifre
            Değiştir</a></li>
        <li><a href="" class="profile-link" data-target-id="settings"><i
                class="glyphicon glyphicon-cog"></i> Ayarlar</a></li>
        <li><a href="" class="profile-link" data-target-id="logout"><i
                class="glyphicon glyphicon-log-out"></i> Çıkış</a></li>
    </ul>
</div>

<div class="col-md-5  admin-content" id="profile">
    <div class="panel panel-info" style="margin: 1em;">
        <div class="panel-heading">
            <h3 class="panel-title">Kullanıcı Adı</h3>
        </div>
        <div class="panel-body">
            {% for item in user %}
            {{ item.full_name }}

        </div>
    </div>
    <div class="panel panel-info" style="margin: 1em;">
        <div class="panel-heading">
            <h3 class="panel-title">Email</h3>
        </div>
        <div class="panel-body">
            {{ item.email }}
            {% endfor %}
        </div>
    </div>
</div>
<div class="col-md-5  admin-content" id="settings">
    <div class="panel panel-info" style="margin: 1em;">
        <div class="panel-heading">
            <h3 class="panel-title">Bildirimler</h3>
        </div>
        <div class="panel-body">
            <div class="label label-success">İzin ver</div>
        </div>
    </div>
    <div class="panel panel-info" style="margin: 1em;">
        <div class="panel-heading">
            <h3 class="panel-title">Haberler</h3>
        </div>
        <div class="panel-body">
            <div class="badge">Aylık</div>
        </div>
    </div>
</div>

<div class="col-md-5  admin-content" id="change-password">
    <form action="/password" method="post">


        <div class="panel panel-info" style="margin: 1em;">
            <div class="panel-heading">
                <h3 class="panel-title">Yeni Parola</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-sm-10">
                        <input type="password" class="profile-buttons" name="password" id="new_password">
                    </div>
                </div>

            </div>
        </div>


        <div class="panel panel-info" style="margin: 1em;">
            <div class="panel-heading">
                <h3 class="panel-title">Parolayı doğrula</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-sm-10">
                        <input type="password" class="profile-buttons" name="password_confirmation"
                               id="confirm_password">
                    </div>
                </div>
            </div>
        </div>


        <div class="panel panel-info border" style="margin: 1em;">
            <div class="panel-body">
                <div class="form-group">
                    <div class="pull-left">
                        <input type="submit" class="profile-buttons btn btn-primary" name="submit" id="submit"
                               value="Gönder">
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>

<div class="col-md-5  admin-content" id="logout">
    <div class="panel panel-info" style="margin: 1em;">
        <div class="panel-heading">
            <h3 class="panel-title">Çıkış Yap</h3>
        </div>
        <div class="panel-body">
            Çıkış yapmak istediğinize emin misiniz?  
            <a href="{% url 'users:logout' %}" class="label label-danger">
                <span> Evet </span>
            </a>    
            <a href="{% url 'users:profile' %}" class="label label-success"> <span> Hayır </span></a>
        </div>
    </div>
</div>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script>
    $(document).ready(function () {
        var navItems = $('.admin-menu li > a');
        var navListItems = $('.admin-menu li');
        var allWells = $('.admin-content');
        var allWellsExceptFirst = $('.admin-content:not(:first)');
        allWellsExceptFirst.hide();
        navItems.click(function(e)
        {
            e.preventDefault();
            navListItems.removeClass('active');
            $(this).closest('li').addClass('active');
            allWells.hide();
            var target = $(this).attr('data-target-id');
            $('#' + target).show();
        });
    });

</script>

{% endblock %}